server:
  port: 8191
spring:  cloud:    config:      server:        git:          uri: https://github.com/krish/spring-cloud-config-store
          search-paths:          - '*service'
#          username: jathu10061994@gmail.com
#          password: ja4044868
          
