debug: true
server:
  port: 8191
spring:  cloud:    config:      server:        git:          uri: https://github.com/jathu1994/rentacar_config_store
          search-paths:          - 'service-config/*service'
          username: jathu10061994@gmail.com
          password: ja4044868
          
