security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:8192/oauth/authorize
      access-token-uri: http://localhost:8192/oauth/token
    resource:      token-info-uri: http://localhost:8192/oauth/check_token
      
server:  servlet:    session:      cookie:        name: KSESSION