debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: profile
    
server:
  port: 9191

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8192/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin 