management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_krish?createDatabaseIfNotExist=true
    username: root
    password:
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
     
